### ISSUE TITLE
Is it supposed to work with WSL2?

### ISSUE THREAD

**Issue by kumekay** [Chronial/wsl-sudo#1]
I didn't dig deeply into the code, but it looks like it doesn't work,

UAC prompt pops up, but then permissions stay the same. I.e:

```
➜ python ./wsl-sudo.py net.exe sessions
System error 5 has occurred.

Access is denied.

➜ net.exe sessions
System error 5 has occurred.

Access is denied.
```

**Comment by Chronial** [comment]
I am not using WSL2, so I have no reason to assume it does. Given that WSL2 is more of a VM, I am not sure if elevating single WSL2 processes is even possible. But I have not looked into it.

**Comment by IainCoSource** [comment]
WSL2 Ubuntu 18
Traceback (most recent call last):
  File "/home/dev/wsl-sudo/wsl-sudo.py", line 332, in <module>
    main()
  File "/home/dev/wsl-sudo/wsl-sudo.py", line 328, in main
    UnprivilegedClient().main(**vars(args))
  File "/home/dev/wsl-sudo/wsl-sudo.py", line 233, in main
    self.sock, acc = listen_socket.accept()
  File "/usr/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out

**Comment by lweberru** [comment]
I am getting the same error - but found this repo link within a wsl discussion. I removed the timeout setting in the source, but then the process waits forever. What I get is the popup to enter my windows admin credentials. So at least thats a good start.

**Comment by pmorch** [comment]
I concur with @kumekay  that `net.exe sessions` is the same with or without `./wsl-sudo.py`

But e.g.

    vi /mnt/c/Windows/System32/drivers/etc/hosts

does not allow me to save the file, whereas

    wsl-sudo.py vi /mnt/c/Windows/System32/drivers/etc/hosts

does. So it must be at least partially working for WSL2 (and editing the hosts file is what I need wsl-sudo for.. Hurray!)

**Comment by Chronial** [comment]
With #2 merged, WSL2 should now be supported.
